bestsellers95%
VladislavReviakin/BlitzCode pull request #1
Opened 2023-08-25 19:06 UTC by RichardDitrix

95%

2023-08-26 00:23 UTC, VladislavReviakin commented on src/css/bestsellers.css
> +
Чого тут пустий клас?

2023-08-26 00:28 UTC, VladislavReviakin requested changes
Коли закінчиш повидаляй контейнери з css будь ласка, я їх задав до осноного файлу

2023-08-26 08:07 UTC, RichardDitrix commented
+Видаляю, а пустий класс бо ще граюсь з сіткою для виставлення в ПК версіїї


сб, 26 авг. 2023 г. в 03:28, VladislavReviakin ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Повидаляй контейнери з css будь ласка, я їх задав до осноного файлу
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/VladislavReviakin/BlitzCode/pull/1#pullrequestreview-1596634855>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVLD5N6MR44YIOXIMLIG7X3XXE7KTANCNFSM6AAAAAA364UJIA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-27 01:08 UTC, VladislavReviakin approved these changes

2023-08-27 01:09 UTC, merged